# Verify Documentation GitHub action
name: Verify Documentation

on:
  workflow_dispatch:
  pull_request:

env:
  HUMMINGBIRD_VERSION: "2.0"
  DEPLOY_ROOT_FOLDER: false
  DOCC_HTML_DIR: "./scripts/swift-docc-render-artifact/dist"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install rsync 📚
      run: |
        apt-get update && apt-get install -y rsync bc
    - name: Verify
      run: |
        ./scripts/build-docc.sh -e
